# Generated by Django 6.0.6 on 2026-06-07 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('serial_num', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=70)),
                ('status', models.CharField(choices=[('AC', 'ACTIVE'), ('PL', 'PLANNED'), ('DE', 'DECOMISSIONED')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('speed', models.IntegerField()),
                ('status', models.CharField(choices=[('UP', 'UP'), ('DO', 'DOWN'), ('MA', 'MAINTENANCE')], max_length=2)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=70)),
                ('status', models.CharField(choices=[('CON', 'CONNECTED'), ('DIS', 'DISCONNECTED')], max_length=3)),
                ('end_interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connection_ends', to='api.interface')),
                ('start_interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connection_starts', to='api.interface')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site'),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('name', 'device'), name='unique_name'),
        ),
    ]
